'use client';

import { useEffect, useState } from 'react';
import TopicNav from '@/components/TopicNav';
import TopicHeader from '@/components/TopicHeader';
import MetricCard from '@/components/MetricCard';
import LineChart, { Series } from '@/components/charts/LineChart';
import PositiveCallout from '@/components/PositiveCallout';
import ScrollReveal from '@/components/ScrollReveal';
import SectionNav from '@/components/SectionNav';

// ── Types ────────────────────────────────────────────────────────────────────

interface TaxEvasionData {
  national: {
    taxGap: {
      timeSeries: Array<{ year: number; gapBillions: number }>;
    };
    hmrcStaff: {
      timeSeries: Array<{ year: number; thousandsFTE: number }>;
    };
  };
  metadata: {
    sources: Array<{ name: string; dataset: string; url: string; frequency: string }>;
    methodology: string;
    knownIssues: string[];
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function yearToDate(y: number): Date {
  return new Date(y, 5, 1);
}

// ── Page ─────────────────────────────────────────────────────────────────────

export default function TaxEvasionPage() {
  const [data, setData] = useState<TaxEvasionData | null>(null);

  useEffect(() => {
    fetch('/data/tax-evasion/tax_evasion.json')
      .then(r => r.json())
      .then(setData)
      .catch(console.error);
  }, []);

  // ── Derived series ──────────────────────────────────────────────────────

  const taxGapSeries: Series[] = data
    ? [{
        id: 'tax-gap',
        label: 'Tax gap (£bn)',
        colour: '#E63946',
        data: data.national.taxGap.timeSeries.map(d => ({
          date: yearToDate(d.year),
          value: d.gapBillions,
        })),
      }]
    : [];

  const hmrcStaffSeries: Series[] = data
    ? [{
        id: 'hmrc-staff',
        label: 'HMRC staff (thousands FTE)',
        colour: '#264653',
        data: data.national.hmrcStaff.timeSeries.map(d => ({
          date: yearToDate(d.year),
          value: d.thousandsFTE,
        })),
      }]
    : [];

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <>
      <TopicNav topic="Tax Evasion" />

      <main className="max-w-5xl mx-auto px-6 py-12">
        <TopicHeader
          topic="Tax Evasion"
          question="How Much Tax Goes Uncollected Every Year?"
          finding="HMRC estimates the UK tax gap at &pound;39.8 billion per year &mdash; the difference between the tax that should be paid under the law and the amount actually collected. This sum exceeds the entire annual budget for policing in England and Wales. Meanwhile, HMRC&apos;s compliance workforce has shrunk, and the number of criminal prosecutions for tax fraud has fallen by over 70% since 2015."
          colour="#E63946"
          preposition="with"
        />

        <section id="sec-context" className="max-w-2xl mt-4 mb-12">
          <div className="text-base text-wiah-black leading-[1.7] space-y-4">
            <p>The UK tax gap &mdash; HMRC&apos;s own estimate of the difference between the theoretical tax liability under the law and the amount actually received &mdash; stood at &pound;39.8 billion in 2022/23, equivalent to 4.8% of total tax liabilities. To put this in context, &pound;39.8 billion is more than the entire Department for Education budget, more than total UK spending on policing, and approximately equal to four years of the NHS capital investment programme. The tax gap comprises several components: criminal evasion (&pound;5.5 billion), avoidance (&pound;1.8 billion), non-payment of assessed liabilities (&pound;4.5 billion), error (&pound;9.7 billion), legal interpretation disputes (&pound;5.2 billion), and the hidden economy (&pound;4.6 billion). Small businesses account for the largest single category by taxpayer type, but the per-taxpayer gap is highest among large businesses and wealthy individuals using complex offshore structures.</p>
            <p>Despite the scale of the problem, HMRC&apos;s enforcement capacity has contracted. The number of HMRC staff fell from 75,000 in 2010 to approximately 60,500 in 2024, a reduction of 19% driven by efficiency programmes and office closures. The number of criminal prosecutions for tax offences has fallen from 1,165 in 2014/15 to approximately 320 in 2023/24 &mdash; a decline of over 70%. The National Audit Office has repeatedly flagged concerns about HMRC&apos;s ability to maintain compliance activity while absorbing budget cuts. HMRC&apos;s compliance yield &mdash; the additional revenue generated by compliance activity &mdash; was &pound;34 billion in 2023/24, meaning that for every pound spent on enforcement, approximately &pound;18 is recovered. This return on investment suggests that increasing compliance spending would be fiscally self-financing, yet HMRC&apos;s compliance headcount has been flat since 2019.</p>
            </div>
        </section>

        <SectionNav sections={[
          { id: 'sec-overview', label: 'Overview' },
          { id: 'sec-gap', label: 'Tax Gap' },
          { id: 'sec-enforcement', label: 'HMRC Capacity' },
        ]} />

        <ScrollReveal>
          <div id="sec-overview" className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-12">
            <MetricCard
              label="UK tax gap"
              value="&pound;39.8bn"
              direction="up"
              polarity="up-is-bad"
              changeText="2022/23 &middot; 4.8% of tax liabilities &middot; Exceeds entire policing budget &middot; Rising in absolute terms since 2020"
              sparklineData={[33, 33, 33, 35, 35, 32, 36, 36, 39.8]}
              onExpand={() => {}}
            />
            <MetricCard
              label="Criminal prosecutions for tax fraud"
              value="~320"
              direction="down"
              polarity="up-is-good"
              changeText="2023/24 &middot; Down 70%+ from 1,165 in 2014/15 &middot; HMRC enforcement capacity reduced"
              sparklineData={[1165, 1020, 870, 730, 620, 510, 420, 380, 320]}
              onExpand={() => {}}
            />
            <MetricCard
              label="HMRC compliance yield"
              value="&pound;34bn"
              direction="flat"
              polarity="up-is-good"
              changeText="2023/24 &middot; &pound;18 returned per &pound;1 spent &middot; Self-financing investment case &middot; Staff cuts limit expansion"
              sparklineData={[28, 29, 30, 30, 31, 30, 32, 33, 34]}
              onExpand={() => {}}
            />
          </div>
        </ScrollReveal>

        <ScrollReveal>
          <section id="sec-gap" className="mb-12">
            <LineChart
              title="UK tax gap, 2015&ndash;2024"
              subtitle="HMRC estimate of the difference between theoretical tax liability and actual receipts (&pound; billions)."
              series={taxGapSeries}
              yLabel="£ billions"
              source={{
                name: 'HMRC',
                dataset: 'Measuring Tax Gaps',
                frequency: 'annual',
              }}
            />
          </section>
        </ScrollReveal>

        <ScrollReveal>
          <section id="sec-enforcement" className="mb-12">
            <LineChart
              title="HMRC staffing, 2015&ndash;2024"
              subtitle="Full-time equivalent staff at HMRC (thousands). Staff cuts have reduced compliance capacity."
              series={hmrcStaffSeries}
              yLabel="Thousands FTE"
              source={{
                name: 'HMRC',
                dataset: 'Annual Report and Accounts',
                frequency: 'annual',
              }}
            />
          </section>
        </ScrollReveal>

        <ScrollReveal>
          <PositiveCallout
            title="What enforcement delivers"
            value="&pound;18"
            unit="returned for every &pound;1 invested in HMRC compliance activity"
            description="HMRC&apos;s compliance yield of &pound;34 billion in 2023/24 demonstrates that tax enforcement is among the most cost-effective forms of public spending. The Common Reporting Standard now enables automatic exchange of financial information with over 100 jurisdictions. The Economic Crime and Corporate Transparency Act 2023 strengthens beneficial ownership disclosure. Making Tax Digital is digitising tax records for 4.2 million self-employed taxpayers. HMRC&apos;s Fraud Investigation Service recovered &pound;1.2 billion from serious and complex tax crime in 2023/24."
            source="Source: HMRC &mdash; Measuring Tax Gaps 2024; NAO &mdash; HMRC Performance Report 2024."
          />
        </ScrollReveal>

        <section className="mt-16 pt-8 border-t border-wiah-border max-w-2xl">
          <h2 className="text-xl font-bold text-wiah-black mb-4">Sources &amp; Methodology</h2>
          <div className="text-sm text-wiah-mid space-y-3 font-mono">
            {data?.metadata.sources.map((src, i) => (
              <div key={i}>
                <a href={src.url} target="_blank" rel="noopener noreferrer" className="text-wiah-blue hover:underline">
                  {src.name} &mdash; {src.dataset}
                </a>
                <div className="text-xs text-wiah-mid">Updated {src.frequency}</div>
              </div>
            ))}
          </div>
          <div className="text-sm text-wiah-mid mt-6 space-y-2">
            <h3 className="font-bold">Methodology</h3>
            <p>{data?.metadata.methodology}</p>
          </div>
          <div className="text-sm text-wiah-mid mt-6 space-y-2">
            <h3 className="font-bold">Known issues</h3>
            <ul className="list-disc list-inside space-y-1">
              {data?.metadata.knownIssues.map((issue, i) => (
                <li key={i}>{issue}</li>
              ))}
            </ul>
          </div>
        </section>
      </main>
    </>
  );
}
