'use client';

import TopicNav from '@/components/TopicNav';
import TopicHeader from '@/components/TopicHeader';
import MetricCard from '@/components/MetricCard';
import LineChart, { Series, Annotation } from '@/components/charts/LineChart';
import ScrollReveal from '@/components/ScrollReveal';
import PositiveCallout from '@/components/PositiveCallout';
import SectionNav from '@/components/SectionNav';
import RelatedTopics from '@/components/RelatedTopics';
import Cite from '@/components/Cite';
import References, { Reference } from '@/components/References';

// Community energy installed capacity MW, 2015–2025 (Community Energy England)
const capacityValues = [120, 145, 158, 162, 170, 178, 185, 195, 230, 280, 350];

// Annual investment £M, 2015–2025
const investmentValues = [95, 105, 88, 72, 78, 105, 98, 120, 145, 180, 215];

// Active project count, 2015–2025
const projectValues = [290, 310, 315, 318, 320, 335, 355, 380, 410, 450, 480];

const series1: Series[] = [{
  id: 'capacity',
  label: 'Installed community energy capacity (MW)',
  colour: '#2A9D8F',
  data: capacityValues.map((v, i) => ({ date: new Date(2015 + i, 5, 1), value: v })),
}];

const series2: Series[] = [
  {
    id: 'investment',
    label: 'Annual investment (£ millions)',
    colour: '#2A9D8F',
    data: investmentValues.map((v, i) => ({ date: new Date(2015 + i, 5, 1), value: v })),
  },
  {
    id: 'projects',
    label: 'Active projects (count)',
    colour: '#264653',
    data: projectValues.map((v, i) => ({ date: new Date(2015 + i, 5, 1), value: v })),
  },
];

const annotations1: Annotation[] = [
  { date: new Date(2015, 5, 1), label: '2015: Feed-in Tariff cuts' },
  { date: new Date(2020, 5, 1), label: '2020: Smart Export Guarantee' },
  { date: new Date(2024, 5, 1), label: '2024: Community Energy Fund' },
];

const annotations2: Annotation[] = [
  { date: new Date(2020, 5, 1), label: '2020: COVID delays' },
  { date: new Date(2022, 5, 1), label: '2022: Energy crisis boost' },
];

const editorialRefs: Reference[] = [
  { num: 1, name: 'Community Energy England', dataset: 'State of the Sector Report', url: 'https://communityenergyengland.org/pages/state-of-the-sector', date: '2025' },
  { num: 2, name: 'DESNZ', dataset: 'Community Energy Fund', url: 'https://www.gov.uk/government/publications/community-energy-fund', date: '2024' },
  { num: 3, name: 'Scottish Government', dataset: 'Community and Renewable Energy Scheme (CARES)', url: 'https://www.gov.scot/policies/renewable-and-low-carbon-energy/community-and-local-energy/', date: '2024' },
];

export default function CommunityEnergyPage() {
  return (
    <>
      <TopicNav topic="Community Energy" />
      <main className="max-w-5xl mx-auto px-6 py-12">
        <TopicHeader
          topic="Community Energy"
          question="Is Britain Building an Energy Democracy?"
          finding="Community energy projects generate 350 MW across the UK — enough to power 350,000 homes — but the sector faces major barriers from grid connection costs and the lack of local supply tariffs."
          colour="#2A9D8F"
          preposition="in"
        />
        <section className="max-w-2xl mt-4 mb-10">
          <div className="text-base text-wiah-black leading-[1.7] space-y-4">
            <p>Community energy — electricity and heat generated by local cooperatives, community benefit societies, and social enterprises — has grown substantially since 2015 but remains a marginal part of the UK energy mix. The 480 organisations tracked by Community Energy England generate around 350 MW: significant in community terms but less than 0.2% of UK generation capacity.<Cite nums={1} /> Solar dominates the technology mix, with a growing number of onshore wind and hydro projects. Scotland has been more supportive, with community energy embedded in national planning policy and dedicated ring-fenced funding through the Community and Renewable Energy Scheme.<Cite nums={3} /></p>
            <p>The sector's fundamental obstacle is the electricity grid. Community generators cannot easily sell power directly to local customers — all generation must go through the national grid and back through licenced suppliers.<Cite nums={1} /> Grid connection costs for new projects can be prohibitive, with waits of 7–10 years for connections in congested areas.<Cite nums={1} /> The Feed-in Tariff cuts of 2015–2019 damaged viability, though the Smart Export Guarantee and rising wholesale prices have improved economics for new projects. Record investment of £215 million in 2025 reflects renewed confidence, but the structural barriers remain: without a local supply licence or community benefit tariff, most projects export cheaply while local residents pay full retail price.<Cite nums={[1, 2]} /></p>
          </div>
        </section>
        <SectionNav sections={[
          { id: 'sec-metrics', label: 'Metrics' },
          { id: 'sec-chart1', label: 'Capacity Growth' },
          { id: 'sec-chart2', label: 'Investment & Projects' },
          { id: 'sec-sources', label: 'Sources' },
        ]} />
        <section id="sec-metrics" className="mb-12">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <MetricCard
              label="Community energy installed capacity (UK)"
              value="350 MW"
              unit=""
              direction="up"
              polarity="up-is-good"
              changeText="+80% since 2020 · could reach 2,000 MW by 2030"
              sparklineData={[170, 178, 185, 195, 230, 280, 350]}
              source="Community Energy England — State of the Sector 2025"
              href="#sec-chart1"
            />
            <MetricCard
              label="Active community energy projects"
              value="480"
              unit=""
              direction="up"
              polarity="up-is-good"
              changeText="up from 320 in 2018 · solar dominant · wind growing"
              sparklineData={[320, 335, 355, 380, 410, 450, 480]}
              source="Community Energy England — State of the Sector 2025"
              href="#sec-chart1"
            />
            <MetricCard
              label="Annual community energy investment"
              value="£215M"
              unit=""
              direction="up"
              polarity="up-is-good"
              changeText="record investment in 2025 · grid connection costs rising"
              sparklineData={[78, 105, 98, 120, 145, 180, 215]}
              source="Community Energy England — State of the Sector 2025"
              href="#sec-chart2"
            />
          </div>
        </section>
        <ScrollReveal>
          <section id="sec-chart1" className="mb-12">
            <LineChart
              title="Community energy installed capacity, UK, 2015–2025"
              subtitle="Total installed generation capacity (MW) from community-owned energy projects. Feed-in Tariff cuts slowed growth 2015–2019; Smart Export Guarantee and energy prices drove recovery."
              series={series1}
              annotations={annotations1}
              yLabel="MW"
              source={{ name: 'Community Energy England', dataset: 'State of the Sector Report', url: 'https://communityenergyengland.org/pages/state-of-the-sector', frequency: 'annual', date: '2025' }}
            />
          </section>
        </ScrollReveal>
        <ScrollReveal>
          <section id="sec-chart2" className="mb-12">
            <LineChart
              title="Annual investment and active projects, UK community energy, 2015–2025"
              subtitle="Annual investment raised (£ millions) and number of active community energy projects. 2020 dip reflects COVID-19 construction delays. Investment recovered to record levels in 2025."
              series={series2}
              annotations={annotations2}
              yLabel="£M / Projects"
              source={{ name: 'Community Energy England', dataset: 'State of the Sector Report', url: 'https://communityenergyengland.org/pages/state-of-the-sector', frequency: 'annual', date: '2025' }}
            />
          </section>
        </ScrollReveal>
        <ScrollReveal>
          <PositiveCallout
            title="Community Energy Fund and local supply reform"
            value="£10M"
            unit="Community Energy Fund launched 2024"
            description="The Community Energy Fund launched in 2024 with £10 million to support new projects through development costs and grid connection. Local Electricity Bill campaigners secured an amendment requiring Ofgem to enable local energy tariffs — the first step towards allowing community generators to sell power directly to local customers. Scotland's Community and Renewable Energy Scheme (CARES) continues to provide a working model for English policy."
            source="Source: DESNZ — Community Energy Fund prospectus 2024. Ofgem — Local Electricity Bill amendments."
          />
        </ScrollReveal>
        <div className="mt-6">
          <References items={editorialRefs} />
        </div>

        <section id="sec-sources" className="mt-16 pt-8 border-t border-wiah-border max-w-2xl">
          <h2 className="text-xl font-bold text-wiah-black mb-4">Sources &amp; Methodology</h2>
          <div className="text-sm text-wiah-mid font-mono space-y-3">
            <p><a href="https://communityenergyengland.org/pages/state-of-the-sector" target="_blank" rel="noopener noreferrer" className="text-wiah-blue hover:underline">Community Energy England — State of the Sector Report</a> — annual survey of UK community energy organisations. Updated annually.</p>
            <p><a href="https://www.gov.uk/government/publications/community-energy-fund" target="_blank" rel="noopener noreferrer" className="text-wiah-blue hover:underline">DESNZ — Community Energy Fund</a> — prospectus and programme data. Retrieved 2025.</p>
            <p><a href="https://www.gov.scot/policies/renewable-and-low-carbon-energy/community-and-local-energy/" target="_blank" rel="noopener noreferrer" className="text-wiah-blue hover:underline">Scottish Government — Community and Renewable Energy Scheme (CARES)</a> — Scottish community energy support programme.</p>
            <p>Capacity figures are for UK. Project count excludes projects under development. Investment figures include equity raised through community share offers and grant funding. Feed-in Tariff data is for England, Scotland, and Wales.</p>
          </div>
        </section>
        <RelatedTopics />
      </main>
    </>
  );
}
